### ISSUE TITLE
Updating a Frame Possible?

### ISSUE THREAD

**Issue by FaizShah** [PixelyIon/ZRA#2]
Hi,

Thanks for this great project, I have been looking for something exactly like this.

I was wondering do you think it would be possible to random access a frame and update the source data in the frame without decompressing the whole file?

Basically I have some very large archives and a small subset of the data in the archive needs to be updated so it would be more efficient to update a frame with random access if possible. Here I can seek the frame but I'm unclear if it's possible to update the frame.

Thanks! Sorry for the weird question.

**Comment by PixelyIon** [comment]
Sorry, due to never actually finding time to work on the project again, it's pretty much in maintenance mode. I think that it's in theory possible to update individual frames but that would require a decent bit of effort, I'm open to PRs regarding this but unfortunately cannot invest the time required to do so.
